// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using sprinkler_scheduling_service.Models;

namespace sprinklerschedulingservice.Migrations
{
    [DbContext(typeof(WebApiContext))]
    [Migration("20180824085124_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("sprinkler_scheduling_service.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Run");

                    b.HasKey("Id");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("sprinkler_scheduling_service.Models.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<List<string>>("Days");

                    b.Property<int>("Duration");

                    b.Property<int?>("ScheduleId");

                    b.Property<DateTime>("StartTime");

                    b.Property<int>("ZoneNumber");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.ToTable("Section");
                });

            modelBuilder.Entity("sprinkler_scheduling_service.Models.Section", b =>
                {
                    b.HasOne("sprinkler_scheduling_service.Models.Schedule")
                        .WithMany("Sections")
                        .HasForeignKey("ScheduleId");
                });
#pragma warning restore 612, 618
        }
    }
}
