// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using sprinkler_scheduling_service.Models;

namespace sprinklerschedulingservice.Migrations
{
    [DbContext(typeof(WebApiContext))]
    partial class WebApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("sprinkler_scheduling_service.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<bool>("Run")
                        .HasColumnName("run");

                    b.HasKey("Id");

                    b.ToTable("schedules");
                });

            modelBuilder.Entity("sprinkler_scheduling_service.Models.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<List<string>>("Days")
                        .HasColumnName("days");

                    b.Property<int>("Duration")
                        .HasColumnName("duration");

                    b.Property<int>("ScheduleId")
                        .HasColumnName("scheduleid");

                    b.Property<string>("StartTime")
                        .HasColumnName("starttime");

                    b.Property<int>("ZoneNumber")
                        .HasColumnName("zonenumber");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.ToTable("section");
                });

            modelBuilder.Entity("sprinkler_scheduling_service.Models.Section", b =>
                {
                    b.HasOne("sprinkler_scheduling_service.Models.Schedule")
                        .WithMany("Sections")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
